In [1]:
versioninfo()

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 80 × Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 1 on 80 virtual cores
Environment:
  LD_LIBRARY_PATH = /cm/shared/apps/slurm/19.05.8/lib64/slurm:/cm/shared/apps/slurm/19.05.8/lib64
  LD_LIBRARY_PATH_modshare = /cm/shared/apps/slurm/19.05.8/lib64:1:/cm/shared/apps/slurm/19.05.8/lib64/slurm:1


# Linear Algebra

## Vectors and Matrices

In [2]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
x = zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [4]:
x = ones(4)

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [5]:
x = fill(2, 4)

4-element Vector{Int64}:
 2
 2
 2
 2

In [6]:
x = rand(4)

4-element Vector{Float64}:
 0.05872377987996846
 0.7382417179237523
 0.055602983406921935
 0.41802712928295216

In [7]:
x = randn(4)

4-element Vector{Float64}:
 -0.6413524963482176
  0.8124351535237249
  1.106727011759173
 -0.04196788455593918

In [8]:
x = randn(10)

10-element Vector{Float64}:
  1.456397278979576
 -1.234769308046188
 -1.1585689715893084
  0.5360179352669974
  0.18600559155443305
  0.391844433849708
  1.3352225710423682
 -1.8704170376120062
  0.36127418097056624
  0.7174534600101058

In [9]:
A = [1 2; 3 4; 5 6]

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

In [10]:
A = zeros(4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [11]:
using LinearAlgebra

In [12]:
A + I

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

`I` is the identity matrix

In [13]:
typeof(I)

UniformScaling{Bool}

In [14]:
A = randn(10, 10)

10×10 Matrix{Float64}:
 -0.215616    2.84276    1.52332      …   0.0846442  -0.870649  -1.16223
  1.70084    -0.429761   0.321637         0.236268    0.34408    0.945413
  0.538355    0.613088  -1.07568         -0.888946   -1.61991   -1.37272
 -1.06411     2.14757    0.975868         1.6174      0.4008    -1.42881
  0.567248   -1.63983    0.359231         0.119521   -0.604175   0.964193
 -0.0527969  -0.311561   0.0145758    …   1.68676     0.105555   1.4698
  0.326927    0.562089   0.198088        -0.177654    0.186475  -0.187463
  1.94358     1.71011   -0.000857477      1.23853    -1.28336   -1.25694
  0.154311    1.54749    1.49545          0.278938   -0.114487   2.1613
  0.190767   -1.00621   -1.29243          0.0326661  -0.878542  -0.727134

In [15]:
A * x

10-element Vector{Float64}:
 -7.589066181331697
  3.1616056789904885
 -2.3054937970686273
 -8.929672697276898
  4.020199565721771
 -2.191182263627267
 -0.2641023949755267
 -1.8934532147192744
 -3.4270909249500385
  4.883339307706483

In [16]:
x * A

LoadError: DimensionMismatch: A has dimensions (10,1) but B has dimensions (10,10)

In [17]:
x' * A

1×10 adjoint(::Vector{Float64}) with eltype Float64:
 -6.52962  2.07363  3.54238  2.38626  …  -0.0179804  2.30545  1.07961

`'`is the transpose

In [18]:
transpose(A)

10×10 transpose(::Matrix{Float64}) with eltype Float64:
 -0.215616    1.70084     0.538355  …   1.94358       0.154311   0.190767
  2.84276    -0.429761    0.613088      1.71011       1.54749   -1.00621
  1.52332     0.321637   -1.07568      -0.000857477   1.49545   -1.29243
 -0.610338   -1.27221    -2.75142       0.0883784     0.488929  -0.120705
 -0.11605    -0.266658    0.302813     -0.474778      0.656373  -0.160339
 -0.505849    0.0317595  -0.497315  …   0.108504      0.552021   1.10207
 -0.109617    0.662735   -1.54134       0.799074     -1.19566    1.81884
  0.0846442   0.236268   -0.888946      1.23853       0.278938   0.0326661
 -0.870649    0.34408    -1.61991      -1.28336      -0.114487  -0.878542
 -1.16223     0.945413   -1.37272      -1.25694       2.1613    -0.727134

In [19]:
y = randn(10)

10-element Vector{Float64}:
  1.7168962785395152
  0.3442702014016139
  0.8366762326618137
 -0.9250479232856191
  1.5466251105201574
  0.23099966610668507
  0.9741443483154738
  1.2049946145203345
  1.4480571975965146
 -0.7923698952804535

In [20]:
y' * A * x

-11.269099832992316

In [21]:
y[1] * A[2, 3] * x[4]

0.29599801314047486

In [22]:
typeof(x)

Vector{Float64} (alias for Array{Float64, 1})

In [23]:
typeof(x')

Adjoint{Float64, Vector{Float64}}

In [24]:
typeof(x'')

Vector{Float64} (alias for Array{Float64, 1})

In [25]:
M = [1;2;; 3;4;;; 5;6;; 7;8]

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

In [26]:
reshape(M, (4,2))

4×2 Matrix{Int64}:
 1  5
 2  6
 3  7
 4  8

In [27]:
reshape(M, (2,4))

2×4 Matrix{Int64}:
 1  3  5  7
 2  4  6  8

In [28]:
Avec = reshape(A, 100)

100-element Vector{Float64}:
 -0.2156155144909075
  1.700836307360281
  0.5383552303090214
 -1.0641124665496406
  0.5672484378785738
 -0.052796884146976836
  0.32692741584939194
  1.9435847899068235
  0.15431051986200553
  0.19076742872546087
  2.842758957511103
 -0.42976068584451127
  0.6130882055111129
  ⋮
 -0.11448739947581711
 -0.8785423132764659
 -1.162226051025465
  0.9454125301367104
 -1.3727185200538567
 -1.4288072832279741
  0.964192802595294
  1.46980178402638
 -0.18746258469529833
 -1.2569407982276775
  2.161300772521143
 -0.7271339892512577

In [29]:
reshape(Avec, (10, 10)) == A

true

## Matrix types

- dense (full)
- symmetric
- triangular
- diagonal
- bi-, tri-diagonal
- sparse

In [30]:
Symmetric(A)

10×10 Symmetric{Float64, Matrix{Float64}}:
 -0.215616    2.84276     1.52332   …   0.0846442  -0.870649  -1.16223
  2.84276    -0.429761    0.321637      0.236268    0.34408    0.945413
  1.52332     0.321637   -1.07568      -0.888946   -1.61991   -1.37272
 -0.610338   -1.27221    -2.75142       1.6174      0.4008    -1.42881
 -0.11605    -0.266658    0.302813      0.119521   -0.604175   0.964193
 -0.505849    0.0317595  -0.497315  …   1.68676     0.105555   1.4698
 -0.109617    0.662735   -1.54134      -0.177654    0.186475  -0.187463
  0.0846442   0.236268   -0.888946      1.23853    -1.28336   -1.25694
 -0.870649    0.34408    -1.61991      -1.28336    -0.114487   2.1613
 -1.16223     0.945413   -1.37272      -1.25694     2.1613    -0.727134

In [31]:
Symmetric(A) - A

10×10 Matrix{Float64}:
  0.0        0.0        0.0        …   0.0        0.0      0.0      0.0
  1.14192    0.0        0.0            0.0        0.0      0.0      0.0
  0.984964  -0.291452   0.0            0.0        0.0      0.0      0.0
  0.453774  -3.41978   -3.72729        0.0        0.0      0.0      0.0
 -0.683299   1.37317   -0.0564181      0.0        0.0      0.0      0.0
 -0.453052   0.343321  -0.51189    …   0.0        0.0      0.0      0.0
 -0.436545   0.100646  -1.73943        0.0        0.0      0.0      0.0
 -1.85894   -1.47384   -0.888089      -0.976727   0.0      0.0      0.0
 -1.02496   -1.20341   -3.11536        1.38213   -1.5623   0.0      0.0
 -1.35299    1.95162   -0.0802846     -2.00631   -1.28961  3.03984  0.0

In [32]:
Symmetric(A + A')

10×10 Symmetric{Float64, Matrix{Float64}}:
 -0.431231   4.5436      2.06167   …   2.02823   -0.716338   -0.971459
  4.5436    -0.859521    0.934725      1.94638    1.89157    -0.0607953
  2.06167    0.934725   -2.15136      -0.889804  -0.124455   -2.66515
 -1.67445    0.875367   -1.77555       1.70578    0.889729   -1.54951
  0.451198  -1.90649     0.662043     -0.355257   0.0521981   0.803854
 -0.558646  -0.279802   -0.482739  …   1.79526    0.657576    2.57187
  0.21731    1.22482    -1.34325       0.62142   -1.00918     1.63138
  2.02823    1.94638    -0.889804      2.47706   -1.00442    -1.22427
 -0.716338   1.89157    -0.124455     -1.00442   -0.228975    1.28276
 -0.971459  -0.0607953  -2.66515      -1.22427    1.28276    -1.45427

In [33]:
Diagonal(randn(10))

10×10 Diagonal{Float64, Vector{Float64}}:
 1.12375    ⋅         ⋅       ⋅        …    ⋅          ⋅        ⋅ 
  ⋅       -0.470012   ⋅       ⋅             ⋅          ⋅        ⋅ 
  ⋅         ⋅        1.7962   ⋅             ⋅          ⋅        ⋅ 
  ⋅         ⋅         ⋅      0.527894       ⋅          ⋅        ⋅ 
  ⋅         ⋅         ⋅       ⋅             ⋅          ⋅        ⋅ 
  ⋅         ⋅         ⋅       ⋅        …    ⋅          ⋅        ⋅ 
  ⋅         ⋅         ⋅       ⋅             ⋅          ⋅        ⋅ 
  ⋅         ⋅         ⋅       ⋅           -0.989262    ⋅        ⋅ 
  ⋅         ⋅         ⋅       ⋅             ⋅        -0.85942   ⋅ 
  ⋅         ⋅         ⋅       ⋅             ⋅          ⋅       0.4533

## Operations on matrices

In [34]:
inv(A)

10×10 Matrix{Float64}:
 -0.0603631   0.108958   -0.0893174   …   0.340931   -0.13597    -0.291706
 -0.477263    0.770444    0.342406       -0.206574    0.910364    0.686947
  1.06798    -0.797125   -0.588983        0.206366   -1.05805    -0.877782
 -0.138666   -0.0830638  -0.108608        0.160631    0.122911   -0.0225467
 -0.0750884  -1.50055    -0.353561        0.558826   -0.438006   -0.698015
  0.425168   -0.265067   -0.268286    …   0.0554592  -0.359629   -0.0657465
 -0.105593    0.34329    -0.00660373     -0.159042    0.324106    0.535303
 -0.0309509  -0.890477   -0.18938         0.423808   -0.466581   -0.527276
 -0.264381    0.239248   -0.139576       -0.0428192  -0.0659677  -0.161161
 -0.515772    0.851842    0.382606       -0.384388    0.985749    0.725855

In [35]:
inv(A) * A == I

false

In [36]:
inv(A) * A

10×10 Matrix{Float64}:
  1.0           3.13652e-16   6.41646e-18  …  -2.56656e-16   8.03909e-17
 -7.11477e-17   1.0           2.29408e-16     -9.87266e-16   1.73657e-16
  2.28619e-16  -7.5154e-16    1.0              1.1485e-15   -6.40503e-16
 -5.2227e-17    7.09784e-17   3.11332e-17     -2.26151e-16   4.87342e-17
  9.64537e-17  -5.06137e-16  -2.51105e-16      3.31916e-16  -3.92085e-16
  1.59194e-18  -1.18392e-16   5.59012e-17  …   4.31183e-16  -4.11068e-16
 -1.04298e-16   1.86048e-16  -4.68579e-17     -1.9283e-16   -7.04297e-17
  8.33399e-17   1.56759e-16   9.84767e-17      8.64394e-16  -4.19678e-16
 -4.00442e-17   1.57086e-16   4.94914e-17      1.0           1.23331e-16
 -3.27509e-17   7.58606e-16   2.34019e-16     -3.12417e-16   1.0

In [37]:
B = big.(rand(-100:100, 10, 10)) // 100

10×10 Matrix{Rational{BigInt}}:
  31//50   -53//100   79//100   11//50   …  -39//100   27//100  -11//50
 -67//100   -1//20   -21//100   -8//25       23//50   -21//50    39//100
   7//100   69//100  -89//100  -57//100     -37//100   19//50    -1//5
  11//25    27//50    43//50    39//100     -13//50    57//100  -69//100
  51//100   29//50   -21//25     3//10      -37//50    -4//5    -73//100
 -33//50   -51//100   -9//50    31//50   …    9//100   81//100   29//50
  21//100  -21//25     2//5     -3//100      13//20   -33//50    29//100
 -89//100    1//5     63//100   43//50       -1//50     7//10    47//100
 -13//50    31//100  -53//100   41//50       -7//50    27//50   -41//50
  21//25    -2//5      1//4     12//25      -31//100   71//100   -1//25

In [38]:
invB = inv(B)

10×10 Matrix{Rational{BigInt}}:
  -2610393987763394888//3687454502839697033   …   3907168699445214296//3687454502839697033
  -8146580070867791072//11062363508519091099      6669755046737221724//11062363508519091099
   4371909474674960228//11062363508519091099     -3756679440208299176//11062363508519091099
  -4130406791828528056//11062363508519091099     10700204520423149452//11062363508519091099
   1039712242136634316//11062363508519091099       639298720842120428//11062363508519091099
  -2754985694628200852//11062363508519091099  …  -4594332421874992816//11062363508519091099
   2149600119706174864//11062363508519091099      -464563827306583888//11062363508519091099
 -13238888248857174016//11062363508519091099      6865566844725797272//11062363508519091099
  -1393674735991029724//11062363508519091099      1651456705768204108//11062363508519091099
  -5295283402966583024//11062363508519091099      9868606331938360208//11062363508519091099

In [39]:
invB * B == I

true

## Floating point numbers

internal representation: m * 2^e

- double precision, 64 bits: m as 53 bits, e as 11 bits
- single precision, 32 bits
- half precision, 16 bits
- ... 8 bits ...

In [40]:
isapprox(inv(A) * A, I)

true

In [41]:
inv(A) * A ≈ I

true

\approx

In [42]:
⌣ = 42

42

In [43]:
⌣

42

In [44]:
# ẋ x′

In [45]:
Rational(0.1)

3602879701896397//36028797018963968

In [46]:
float(Rational(0.1) - 1//10)

5.551115123125783e-18

In [47]:
π

π = 3.1415926535897...

In [48]:
Float64(π)

3.141592653589793

In [49]:
BigFloat(π)

3.141592653589793238462643383279502884197169399375105820974944592307816406286198

In [50]:
isapprox(1, 1.00001; atol=1e-3)

true

In [51]:
const tol = 1e-3

0.001

In [52]:
myisapprox(a,b) = isapprox(a, b; atol=tol)

myisapprox (generic function with 1 method)

In [53]:
myisapprox(1, 1.00001)

true

# Least Squares

In [71]:
# expansion coefficients
pmax = 4

4

In [ ]:
# evaluation points
npoints = 11
x = LinRange(0, π/2, npoints-1)

In [ ]:
# target function
fstar(x) = sin(x)

In [ ]:
# matrix
A = [x[i]^p for i in 1:npoints, p in 0:pmax]

In [ ]:
c = (A'*A) \ (A'*b)

## Solving linear systems

In [69]:
A = randn(10,10)
b = randn(10)

10-element Vector{Float64}:
 -0.5022188249828673
 -1.4684624820836565
 -0.732304730684058
 -0.9718000241141903
 -0.9702373112857338
  1.3572045988513857
  1.4784143973334847
 -0.17832791497581194
 -0.5122614326288
  2.659881965797241

In [62]:
2 / 3

0.6666666666666666

In [63]:
2 \ 3

1.5

In [67]:
x = A \ b

10-element Vector{Float64}:
 -0.9063723567849704
 -0.930448325898977
 -1.6857217510127993
 -0.3235371956379028
 -1.509754594119294
  0.2849739657226849
 -1.0920555313836793
  1.5372840342353487
 -0.004295349465374819
  0.911999627253853

In [68]:
A * x ≈ b

true