In [1]:
versioninfo()

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 80 × Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 1 on 80 virtual cores
Environment:
  LD_LIBRARY_PATH = /cm/shared/apps/slurm/19.05.8/lib64/slurm:/cm/shared/apps/slurm/19.05.8/lib64
  LD_LIBRARY_PATH_modshare = /cm/shared/apps/slurm/19.05.8/lib64:1:/cm/shared/apps/slurm/19.05.8/lib64/slurm:1


# Linear Algebra

## Vectors and Matrices

In [2]:
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
x = zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [4]:
x = ones(4)

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [5]:
x = fill(2, 4)

4-element Vector{Int64}:
 2
 2
 2
 2

In [6]:
x = rand(4)

4-element Vector{Float64}:
 0.8996499963459214
 0.037786892549404816
 0.4031264941850953
 0.6126642300955146

In [7]:
x = randn(4)

4-element Vector{Float64}:
 -1.6270848327891831
  1.1341852825843286
 -0.6707704024853621
  0.8315451989225884

In [8]:
x = randn(10)

10-element Vector{Float64}:
  2.4031098610545567
 -0.8311256525693046
  0.8895785144920922
  0.3185303813690472
 -0.7573750004106052
 -0.28919400077453383
  1.3414124451209453
 -0.8936380792982158
  0.22985102421678671
  0.23114761882433152

In [9]:
A = [1 2; 3 4; 5 6]

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

In [10]:
A = zeros(4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [11]:
using LinearAlgebra

In [12]:
A + I

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

`I` is the identity matrix

In [13]:
typeof(I)

UniformScaling{Bool}

In [14]:
A = randn(10, 10)

10×10 Matrix{Float64}:
  0.296304   1.58341   -0.0366465  …   0.371724   0.849471    0.770309
 -0.718527  -0.348199  -0.593788      -1.75289   -0.0250053   0.669898
  1.63976   -1.14159   -2.18676       -0.480174  -0.0505617   1.03186
  1.19449    1.26358   -0.355305      -0.18366   -1.17637     0.0330279
  0.584364  -1.21314   -1.54054        1.10834    0.35221     0.430457
 -0.404281   0.58967   -1.15768    …   0.39554   -0.931908   -1.32072
  0.568006  -0.776559   1.68858       -0.478255   1.25104    -0.120637
 -0.353696   0.563102   1.65967        0.245993  -0.0646085   0.637171
  0.21396    0.551533   0.765455      -0.565634  -1.05752     0.743447
 -1.15849   -1.72129    0.419384       0.129274   0.618487   -1.09672

In [15]:
A * x

10-element Vector{Float64}:
  0.595284840703115
  0.8707917302224613
  1.040319829708752
  4.426826334267087
  1.6726641387889751
 -6.680234641939456
  4.467938031395946
  1.8729955422060924
  0.03384557608099926
 -2.5818355881566055

In [16]:
x * A

LoadError: DimensionMismatch: A has dimensions (10,1) but B has dimensions (10,10)

In [17]:
x' * A

1×10 adjoint(::Vector{Float64}) with eltype Float64:
 3.68215  2.41373  0.903346  -2.0041  -1.78297  …  -0.0508056  3.281  1.46489

`'`is the transpose

In [18]:
transpose(A)

10×10 transpose(::Matrix{Float64}) with eltype Float64:
  0.296304   -0.718527    1.63976    …  -0.353696    0.21396   -1.15849
  1.58341    -0.348199   -1.14159        0.563102    0.551533  -1.72129
 -0.0366465  -0.593788   -2.18676        1.65967     0.765455   0.419384
 -1.33303    -0.0439847  -0.333462       0.18874     1.11422   -1.44606
 -1.51272    -1.2254      0.851784      -0.347078    0.338082  -0.968395
 -0.273615    1.41344     1.44648    …  -1.03301     0.430552   0.654453
  0.291119    0.458807   -1.03626        0.879845   -0.82857   -1.08709
  0.371724   -1.75289    -0.480174       0.245993   -0.565634   0.129274
  0.849471   -0.0250053  -0.0505617     -0.0646085  -1.05752    0.618487
  0.770309    0.669898    1.03186        0.637171    0.743447  -1.09672

In [19]:
y = randn(10)

10-element Vector{Float64}:
 -0.21119388828990185
  0.8577502490671166
  1.2251630385390737
 -0.25039139710348385
  1.3900015582721716
  0.16212214612351294
  1.8963374336848673
 -1.012085380078857
  0.2572364279740445
 -0.7854637641701424

In [20]:
y' * A * x

10.643046608741834

In [21]:
y[1] * A[2, 3] * x[4]

0.03994512192215165

In [22]:
typeof(x)

Vector{Float64} (alias for Array{Float64, 1})

In [23]:
typeof(x')

Adjoint{Float64, Vector{Float64}}

In [24]:
typeof(x'')

Vector{Float64} (alias for Array{Float64, 1})

In [25]:
M = [1;2;; 3;4;;; 5;6;; 7;8]

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

In [26]:
reshape(M, (4,2))

4×2 Matrix{Int64}:
 1  5
 2  6
 3  7
 4  8

In [27]:
reshape(M, (2,4))

2×4 Matrix{Int64}:
 1  3  5  7
 2  4  6  8

In [28]:
Avec = reshape(A, 100)

100-element Vector{Float64}:
  0.29630444344558654
 -0.7185265459620173
  1.6397621087291334
  1.194488422209539
  0.5843637453138649
 -0.4042812742623216
  0.5680057203679018
 -0.35369590869885176
  0.21396014655626866
 -1.1584898504712184
  1.5834081076636604
 -0.3481985271752315
 -1.1415892347572683
  ⋮
 -1.0575175792521956
  0.6184869924734187
  0.7703089962902211
  0.6698975836988228
  1.031864800057134
  0.033027858763592356
  0.43045723347533243
 -1.3207192368572802
 -0.12063698007085714
  0.6371707044713242
  0.743447228519722
 -1.0967210981132254

In [29]:
reshape(Avec, (10, 10)) == A

true

## Matrix types

- dense (full)
- symmetric
- triangular
- diagonal
- bi-, tri-diagonal
- sparse

In [30]:
Symmetric(A)

10×10 Symmetric{Float64, Matrix{Float64}}:
  0.296304    1.58341    -0.0366465  …   0.371724    0.849471    0.770309
  1.58341    -0.348199   -0.593788      -1.75289    -0.0250053   0.669898
 -0.0366465  -0.593788   -2.18676       -0.480174   -0.0505617   1.03186
 -1.33303    -0.0439847  -0.333462      -0.18366    -1.17637     0.0330279
 -1.51272    -1.2254      0.851784       1.10834     0.35221     0.430457
 -0.273615    1.41344     1.44648    …   0.39554    -0.931908   -1.32072
  0.291119    0.458807   -1.03626       -0.478255    1.25104    -0.120637
  0.371724   -1.75289    -0.480174       0.245993   -0.0646085   0.637171
  0.849471   -0.0250053  -0.0505617     -0.0646085  -1.05752     0.743447
  0.770309    0.669898    1.03186        0.637171    0.743447   -1.09672

In [31]:
Symmetric(A) - A

10×10 Matrix{Float64}:
  0.0        0.0         0.0        …   0.0      0.0       0.0      0.0
  2.30193    0.0         0.0            0.0      0.0       0.0      0.0
 -1.67641    0.547801    0.0            0.0      0.0       0.0      0.0
 -2.52752   -1.30757     0.0218433      0.0      0.0       0.0      0.0
 -2.09709   -0.0122651   2.39232        0.0      0.0       0.0      0.0
  0.130667   0.823773    2.60416    …   0.0      0.0       0.0      0.0
 -0.276887   1.23537    -2.72484        0.0      0.0       0.0      0.0
  0.72542   -2.31599    -2.13985       -1.3581   0.0       0.0      0.0
  0.635511  -0.576539   -0.816017       2.07961  0.501025  0.0      0.0
  1.9288     2.39119     0.612481       0.96645  0.507896  0.12496  0.0

In [32]:
Symmetric(A + A')

10×10 Symmetric{Float64, Matrix{Float64}}:
  0.592609    0.864882   1.60312   …   0.0180283    1.06343    -0.388181
  0.864882   -0.696397  -1.73538      -1.18979      0.526528   -1.05139
  1.60312    -1.73538   -4.37352       1.1795       0.714893    1.45125
 -0.138545    1.2196    -0.688766      0.00507948  -0.0621534  -1.41303
 -0.928358   -2.43854   -0.688754      0.761267     0.690292   -0.537938
 -0.677896    2.00311    0.288806  …  -0.637473    -0.501357   -0.666266
  0.859124   -0.317752   0.652312      0.40159      0.422469   -1.20772
  0.0180283  -1.18979    1.1795        0.491986    -0.630242    0.766445
  1.06343     0.526528   0.714893     -0.630242    -2.11504     1.36193
 -0.388181   -1.05139    1.45125       0.766445     1.36193    -2.19344

In [33]:
Diagonal(randn(10))

10×10 Diagonal{Float64, Vector{Float64}}:
 -1.28027   ⋅          ⋅        ⋅        …   ⋅         ⋅         ⋅ 
   ⋅       0.311793    ⋅        ⋅            ⋅         ⋅         ⋅ 
   ⋅        ⋅        -0.71666   ⋅            ⋅         ⋅         ⋅ 
   ⋅        ⋅          ⋅       0.129255      ⋅         ⋅         ⋅ 
   ⋅        ⋅          ⋅        ⋅            ⋅         ⋅         ⋅ 
   ⋅        ⋅          ⋅        ⋅        …   ⋅         ⋅         ⋅ 
   ⋅        ⋅          ⋅        ⋅            ⋅         ⋅         ⋅ 
   ⋅        ⋅          ⋅        ⋅           0.632835   ⋅         ⋅ 
   ⋅        ⋅          ⋅        ⋅            ⋅        0.668391   ⋅ 
   ⋅        ⋅          ⋅        ⋅            ⋅         ⋅        0.55212

## Operations on matrices

In [34]:
inv(A)

10×10 Matrix{Float64}:
  0.00101914  -0.285023     0.69748    …   0.593993   -0.538448    0.300498
  0.125063     0.225304    -0.238509       0.0690827  -0.0197511  -0.581498
 -0.226224     0.172822     0.16443        1.01772    -0.220016   -0.226735
  0.404727    -0.625374    -0.724689      -2.30047     1.19091     0.579716
 -0.409289     0.361501     0.135313       0.938223   -0.478565   -0.802376
 -0.607572     1.03144     -0.51517    …   1.0184     -0.0360128  -1.75209
 -0.657621     0.785991    -0.0103972      1.51675    -0.856465   -1.20964
 -0.255466     0.251168    -0.816973      -0.0515888   0.587149   -1.12298
  0.767698    -0.692621    -0.411867      -2.16205     0.672743    0.786705
  0.235993    -0.00565921  -0.089186      -0.262961    0.644008    0.00560491

In [35]:
inv(A) * A == I

false

In [36]:
inv(A) * A

10×10 Matrix{Float64}:
  1.0           3.36015e-16   1.27889e-16  …   1.73135e-16   1.24729e-16
  1.98073e-16   1.0          -7.15417e-17      4.47584e-17   3.23921e-17
 -1.4191e-17    3.03371e-17   1.0              1.63234e-16   9.42124e-17
 -2.60006e-16   3.01404e-16   7.06905e-16      6.78433e-16   3.20193e-16
  2.43704e-17  -3.04383e-16  -2.39212e-16     -2.44734e-16  -3.71893e-16
 -3.09388e-16  -5.07114e-16  -4.09359e-16  …  -3.25088e-16  -3.0784e-16
  3.47526e-16  -3.16633e-16  -3.24876e-16     -1.30038e-16   3.99725e-16
 -1.93633e-16   1.11291e-16   2.57137e-16     -2.51647e-16  -3.45622e-16
 -8.72742e-17   3.93621e-16   6.30692e-16      1.0          -4.09653e-16
  3.01063e-17  -7.30361e-18   1.00058e-16      6.48516e-17   1.0

In [37]:
B = big.(rand(-100:100, 10, 10)) // 100

10×10 Matrix{Rational{BigInt}}:
 -14//25    91//100   -4//25    53//100  …  -67//100   -7//50     3//25
 -11//25    -7//100   13//50    43//100      31//100   91//100   17//50
   9//50    63//100   27//100  -13//50      -13//20    -4//25   -81//100
  43//100    2//25    -1//20    -7//25      -89//100   22//25    -1//2
  -6//25   -77//100   -1//1     29//100      -4//25    -9//100  -47//100
 -39//100  -11//50    11//100    1//100  …   22//25   -31//100  -41//100
  11//20    21//25   -21//50     1//20       -9//10    -7//10   -31//50
  47//50    -1//4     79//100  -24//25       77//100   -9//100    3//5
   4//5     77//100   24//25     7//25       -3//25   -39//50   -27//100
 -61//100  -11//50    13//100   -7//100      -9//20     9//10    49//50

In [38]:
invB = inv(B)

10×10 Matrix{Rational{BigInt}}:
 -2410189007062999681//917933228412686465  …   -934037199717060714//917933228412686465
   -75801319156842591//131133318344669495       -66616252538013262//393399955034008485
  1212102021310676207//917933228412686465      1486068768579820574//2753799685238059395
 -1441811240570109426//917933228412686465     -1816980485531824232//2753799685238059395
    77762642437147341//917933228412686465       258848411146386262//2753799685238059395
 -1165716921617707177//917933228412686465  …   -217573239641222538//917933228412686465
  -192455979978136349//917933228412686465      1096155899581065182//2753799685238059395
  -878491049907167957//917933228412686465     -1158219939243050074//2753799685238059395
  -700581012821052098//917933228412686465      -302191174220647812//917933228412686465
   -87351152891085207//183586645682537293        34187614172614242//183586645682537293

In [39]:
invB * B == I

true

## Floating point numbers

internal representation: m * 2^e

- double precision, 64 bits: m as 53 bits, e as 11 bits
- single precision, 32 bits
- half precision, 16 bits
- ... 8 bits ...

In [40]:
isapprox(inv(A) * A, I)

true

In [41]:
inv(A) * A ≈ I

true

\approx

In [42]:
⌣ = 42

42

In [43]:
⌣

42

In [44]:
# ẋ x′

In [45]:
Rational(0.1)

3602879701896397//36028797018963968

In [46]:
float(Rational(0.1) - 1//10)

5.551115123125783e-18

In [47]:
π

π = 3.1415926535897...

In [48]:
Float64(π)

3.141592653589793

In [49]:
BigFloat(π)

3.141592653589793238462643383279502884197169399375105820974944592307816406286198

In [50]:
isapprox(1, 1.00001; atol=1e-3)

true

In [51]:
const tol = 1e-3

0.001

In [52]:
myisapprox(a,b) = isapprox(a, b; atol=tol)

myisapprox (generic function with 1 method)

In [53]:
myisapprox(1, 1.00001)

true

# Least Squares

In [100]:
# expansion coefficients
pmax = 10

10

In [101]:
# evaluation points
npoints = 101
x = LinRange(0, 2π, npoints)

101-element LinRange{Float64, Int64}:
 0.0,0.0628319,0.125664,0.188496,0.251327,…,6.09469,6.15752,6.22035,6.28319

In [118]:
# target function
fstar(x) = sin(x)
# fstar(x) = ifelse(x<1, 0, 1)

fstar (generic function with 1 method)

In [111]:
# matrix
A = [x[i]^p for i in 1:npoints, p in 0:pmax]

101×11 Matrix{Float64}:
 1.0  0.0         0.0           0.0         …  0.0          0.0
 1.0  0.0628319   0.00394784    0.00024805     1.52623e-11  9.58956e-13
 1.0  0.125664    0.0157914     0.0019844      7.81428e-9   9.81971e-10
 1.0  0.188496    0.0355306     0.00669736     3.00407e-7   5.66254e-8
 1.0  0.251327    0.0631655     0.0158752      4.00091e-6   1.00554e-6
 1.0  0.314159    0.098696      0.0310063   …  2.98091e-5   9.3648e-6
 1.0  0.376991    0.142122      0.0535788      0.000153808  5.79844e-5
 1.0  0.439823    0.193444      0.0850812      0.000615887  0.000270881
 1.0  0.502655    0.252662      0.127002       0.00204847   0.00102967
 1.0  0.565487    0.319775      0.180829       0.00591291   0.00334367
 1.0  0.628319    0.394784      0.24805     …  0.0152623    0.00958956
 1.0  0.69115     0.477689      0.330155       0.0359876    0.0248728
 1.0  0.753982    0.568489      0.428631       0.0787499    0.059376
 ⋮                                          ⋱               ⋮

In [112]:
b = fstar.(x)

101-element Vector{Int64}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [113]:
c = (A'*A) \ (A'*b)

11-element Vector{Float64}:
  -0.027850745452162547
   1.8421848159706482
 -13.005466490862151
  30.072903298010026
 -31.22635329957057
  17.9023240101014
  -6.179214117504855
   1.3188453042584352
  -0.17058329821007884
   0.012264717463928475
  -0.0003763623849939136

In [114]:
f(c, x) = sum(c[p+1] * x^p for p in 0:pmax)

f (generic function with 1 method)

In [115]:
using WGLMakie

In [116]:
fig = Figure()
Axis(fig[1,1])
xx = LinRange(0, 2π, 201)
yy = [f(c,x) for x in xx]
lines!(xx, fstar.(xx))
lines!(xx, yy)
scatter!(x, [f(c,x′) for x′ in x])
fig

In [117]:
fig = Figure()
Axis(fig[1,1])
xx = LinRange(0, 2π, 201)
yy = [f(c,x) - fstar(x) for x in xx]
lines!(xx, yy)
fig

## Solving linear systems

In [59]:
A = randn(10,10)
b = randn(10)

10-element Vector{Float64}:
 -0.5767506008383114
  0.18444428815123923
  0.8672793379654672
  1.6689889485333602
 -1.0875572368178728
 -0.18317050499982213
  0.21234380495739322
 -2.182370791482697
  1.5878191980893126
  0.9642394668191557

In [60]:
2 / 3

0.6666666666666666

In [61]:
2 \ 3

1.5

In [62]:
x = A \ b

10-element Vector{Float64}:
 -0.38566938137961865
  0.40807731154378574
  0.7373493682294519
  0.08632007030831569
 -0.42514487240116483
  0.31384811859008055
  0.2462259305829138
  0.7155815311061249
 -1.2203707461343676
  1.2959856448643272

In [63]:
A * x ≈ b

true

## Matrix operations

In [119]:
A = randn(10, 10)

10×10 Matrix{Float64}:
  0.549126    0.0998721   0.703103   …  -0.551968  -1.32091   -0.464965
 -1.39443    -0.241709    0.79938        0.623637  -2.03644   -0.495334
  0.274345    0.585941    1.30967        0.199725   0.310771   1.2959
  0.390338   -0.243763   -0.0828302     -1.77996   -1.25528    0.165768
  0.91283    -0.852078   -0.894069      -0.228502  -0.13873   -0.312594
  1.01595     0.170565    1.13128    …  -1.72936    0.403166  -0.749271
 -1.50734    -0.337283    0.596123      -0.219408  -1.04985   -0.43931
 -2.08594     1.13756     0.912189      -0.161296  -0.929213   1.55072
 -0.0980929   1.55993     1.39427       -0.937104  -1.29233   -0.875121
  0.557355    0.855606    0.32229       -1.43361    1.46757    0.738437

- LU decomposition
- A = L * U

In [120]:
lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
10×10 Matrix{Float64}:
  1.0         0.0         0.0        0.0        …   0.0        0.0       0.0
  0.0470257   1.0         0.0        0.0            0.0        0.0       0.0
  0.668489   -0.665251    1.0        0.0            0.0        0.0       0.0
 -0.437611   -0.235171   -0.162671   1.0            0.0        0.0       0.0
 -0.487045    0.48101     0.850215   0.466776       0.0        0.0       0.0
 -0.187128   -0.0205075   0.106173   0.0753791  …   0.0        0.0       0.0
 -0.131521    0.488276    0.707151   0.440826       0.0        0.0       0.0
 -0.263251    0.265088    0.537397   0.265937       1.0        0.0       0.0
 -0.267196    0.769738   -0.435589  -0.389465      -0.721579   1.0       0.0
  0.722617   -0.769569    0.897427  -0.344622       0.889132  -0.696761  1.0
U factor:
10×10 Matrix{Float64}:
 -2.08594  1.13756  0.912189  -1.8858    …  -0.161296  -0.929213    1.55072
  0.0      1.50643  1.35137   -0.966995     

In [121]:
L = lu(A).L
U = lu(A).U;

In [132]:
# Erik forgot to take the permutation into account, so this does not work!
L * U ≈ A

false

In [125]:
A

10×10 Matrix{Float64}:
  0.549126    0.0998721   0.703103   …  -0.551968  -1.32091   -0.464965
 -1.39443    -0.241709    0.79938        0.623637  -2.03644   -0.495334
  0.274345    0.585941    1.30967        0.199725   0.310771   1.2959
  0.390338   -0.243763   -0.0828302     -1.77996   -1.25528    0.165768
  0.91283    -0.852078   -0.894069      -0.228502  -0.13873   -0.312594
  1.01595     0.170565    1.13128    …  -1.72936    0.403166  -0.749271
 -1.50734    -0.337283    0.596123      -0.219408  -1.04985   -0.43931
 -2.08594     1.13756     0.912189      -0.161296  -0.929213   1.55072
 -0.0980929   1.55993     1.39427       -0.937104  -1.29233   -0.875121
  0.557355    0.855606    0.32229       -1.43361    1.46757    0.738437

- QR factorization
- A = Q * R

In [128]:
Q = qr(A).Q
R = qr(A).R;

In [130]:
Q * R ≈ A

true

## Linear Operators and Matrices

In [133]:
using SparseArrays

In [135]:
A = sprandn(10, 10, 1/10)

10×10 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
  ⋅          ⋅         ⋅    ⋅          ⋅   …   ⋅    ⋅    ⋅          ⋅ 
  ⋅          ⋅         ⋅    ⋅          ⋅       ⋅    ⋅    ⋅          ⋅ 
  ⋅          ⋅         ⋅    ⋅          ⋅       ⋅    ⋅    ⋅          ⋅ 
 0.949626    ⋅         ⋅    ⋅          ⋅       ⋅    ⋅    ⋅          ⋅ 
  ⋅          ⋅         ⋅    ⋅          ⋅       ⋅    ⋅   0.332341    ⋅ 
  ⋅          ⋅         ⋅    ⋅          ⋅   …   ⋅    ⋅    ⋅        -0.0662836
  ⋅         1.14216    ⋅    ⋅          ⋅       ⋅    ⋅    ⋅          ⋅ 
  ⋅          ⋅         ⋅   0.0597499   ⋅       ⋅    ⋅    ⋅          ⋅ 
  ⋅        -0.315727   ⋅   0.219145    ⋅       ⋅    ⋅    ⋅          ⋅ 
  ⋅          ⋅         ⋅    ⋅          ⋅       ⋅    ⋅    ⋅          ⋅ 

In [136]:
b = randn(10)

10-element Vector{Float64}:
  0.6044889383812975
 -1.1092870721813701
  0.009836093063123235
  0.4454329795176439
 -1.0580487773352096
 -0.3985351058403686
 -0.07137667894007606
  1.1394964985927887
  1.0092151420200306
  0.12045628243628521

In [137]:
A * b

10-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.5740385607762992
 -0.016058117404607386
 -0.007984277194682367
 -1.2669799298463944
  0.026614553924395684
  0.44784640280689647
  0.0

In [138]:
A = (A + A')^2

10×10 SparseMatrixCSC{Float64, Int64} with 27 stored entries:
 0.90179     ⋅          ⋅   …  0.05674      0.208106     ⋅ 
  ⋅         1.40421     ⋅       ⋅            ⋅           ⋅ 
  ⋅          ⋅          ⋅       ⋅            ⋅           ⋅ 
  ⋅        -0.0691901   ⋅       ⋅            ⋅           ⋅ 
  ⋅        -0.104929    ⋅       ⋅            ⋅         -0.0584544
  ⋅          ⋅          ⋅   …   ⋅           0.293086     ⋅ 
  ⋅          ⋅          ⋅       ⋅          -0.36061      ⋅ 
 0.05674     ⋅          ⋅      0.00357004   0.0130939    ⋅ 
 0.208106    ⋅          ⋅      0.0130939    0.258159     ⋅ 
  ⋅          ⋅          ⋅       ⋅            ⋅          0.00439352

In [140]:
eigvals(Matrix(A))

10-element Vector{Float64}:
 -4.65926389719694e-17
  1.7883899018346986e-16
  0.0004885358325410707
  0.0004885358325412336
  0.8388575250629489
  0.8388575250629492
  0.9719939170088447
  0.9719939170088452
  1.438812959105071
  1.438812959105072

In [142]:
]add Arpack

    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed Arpack_jll ─ v3.5.1+1
   Installed Arpack ───── v0.5.4
    Updating `~/.julia/environments/v1.8/Project.toml`
  [7d9fca2a] + Arpack v0.5.4
    Updating `~/.julia/environments/v1.8/Manifest.toml`
  [7d9fca2a] + Arpack v0.5.4
⌅ [68821587] + Arpack_jll v3.5.1+1
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ✓ Arpack_jll
  ✓ Arpack
  2 dependencies successfully precompiled in 8 seconds. 321 already precompiled.


In [143]:
using Arpack

In [145]:
eigs(A; nev=4)

([1.4388129591050731, 1.438812959105072, 0.9719939170088449, 0.9719939170088447], [0.023697482326410984 0.13119258909936157 -0.5585125933750877 0.6064094335997046; 0.9483946462451319 -0.17130971743255438 0.18175674730054 0.1674008131694976; … ; 0.06074539648543878 0.33629504311983643 -0.17883110602455057 0.1941672775165645; 0.008293760376759702 -0.001498112365164885 -0.02014935660515325 -0.01855787325995381], 4, 1, 10, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

In [146]:
A = sprandn(10^6, 10^6, 10^-6)

1000000×1000000 SparseMatrixCSC{Float64, Int64} with 1000135 stored entries:
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

In [148]:
A = (A + A')^2

1000000×1000000 SparseMatrixCSC{Float64, Int64} with 4861940 stored entries:
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

In [149]:
eigs(A; nev=10)

([33.334526522335864, 33.33452652233579, 32.76803232922468, 32.76803232836849, 32.147098306593044, 32.14709830658906, 31.21063725807284, 31.21063725807278, 31.130768969638165, 31.130768969638073], [-1.1052537336605151e-16 7.219258512980826e-18 … -4.2164421357702855e-17 3.113571609582585e-16; -1.6905562555223892e-16 1.2367896265109581e-16 … 2.20773857970716e-17 -1.2097844626327715e-18; … ; 5.695284603563285e-16 3.030319550512735e-17 … -9.170270374155808e-16 1.5433158417106811e-15; -4.413729363592221e-16 4.7482891401492066e-15 … 2.2126535956227744e-16 -5.696207458926047e-15], 10, 34, 277, [0.0003003455533070884, -0.0021652220582194103, 0.0045355242899022975, 0.007398656959670783, -0.005356622976878885, 0.0007675647359153757, -0.00012144900701438543, -5.3605325191419026e-5, 0.0018973066141221705, -0.0002945052180428473  …  -0.00043990979958500866, 0.002034521326187796, -0.011485548657721995, 0.0010688250160229738, -2.4715069258551916e-5, -0.000882669246324071, -0.000507952775237697, -0.00